name: trackapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3
  flushbar: ^1.9.1
  datetime_picker_formfield: any
  google_sign_in: ^4.1.1
  flutter_facebook_login: ^3.0.0

  json_annotation:
  
  

  flutter_bloc: ^1.0.0
  toast: ^0.1.5
  google_maps_flutter: ^0.5.21+8
  sliding_up_panel: ^0.3.6
  http: ^0.12.0+2


  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_model:
  build_runner:
  json_serializable:

flutter:
  uses-material-design: true